### ISSUE TITLE
Option to disable printing style

### ISSUE THREAD

**Issue by RoiEXLab** [w3c/css-validator#108]
I'd like to have the automatic printing (reverted in https://github.com/w3c/css-validator/commit/1eed592a16936c1577c0cdcd526f49e4d500c7b6) as a cli option, so users can disable it if it's too verbose.
For stuff like travis builds etc. only the error log is needed, when everything works fine the log is not needed and just clutters most of the log.

Low Priority though.

**Comment by sideshowbarker** [comment]
To be clear, do you mean you want an option to disable printing of the stylesheet at the end of the report that the `output=text` (default) and `output=html` output formats add?

If so, 1eed592 didn’t add that back. What 1eed592 did was just to fix a regression that caused the entire error report to never be emitted at all.

If you don’t want the stylesheet printed out at the end of the error report, you can use any of the output formats other than the `output=text` or `output=html` formats — which really are intended only for human consumption anyway, and not for a case like automated checking in Travis or such.

The `output=json` format it relatively terse — but if you want something really terse, you can try the `output=gnu` format, which if there are no errors or warnings will print nothing at all.

**Comment by ylafon** [comment]
You can always redirect the output to /dev/null

**Comment by RoiEXLab** [comment]
I'll try @sideshowbarker's suggestion and report back how well this works out.
@ylafon Redirecting to /dev/null would cause no logs ever to be shown, if errors are being printed to stderr however, your suggestion might work out as well.

**Comment by ylafon** [comment]
@RoiEXLab I was under the impression that you wanted only the return code. If you want the list of errors, as suggested by @sideshowbarker, any specific output (json, soap12, unicorn,...) should provide only a report and the list of warnings and errors.

**Comment by RoiEXLab** [comment]
@sideshowbarker Your suggestion worked perfectly, however you probably should document those output formats in the usage `--help`.
Closing...
