### ISSUE TITLE
Please add support for CSS variables ("custom properties"), a widely supported and crucial feature.

### ISSUE THREAD

**Issue by Hexstream** [w3c/css-validator#111]
Hello,

As can be seen at https://caniuse.com/#feat=css-variables, today CSS variables ("custom properties") is a widely supported feature in all modern standards-compliant browsers. (Of course, Internet Explorer is not in any way modern or standards-compliant.)

I am proudly coding all my sites by hand in raw HTML5/CSS3 according to the W3C standards and recently started using CSS variables heavily (a much-awaited feature!), which results in dozens of validation "errors" whenever someone clicks one of my `✔ CSS3` links in the footer of my pages, which links to the validation results for that page using your validator.

I take pride in having no or very few validation errors in my pages. Having to explain to users that these "errors" are not actual errors and are more akin to a bug in the validator is pretty awkward. So please finally add support for CSS variables, a widely supported and crucial feature.

(edit: I just noticed that the [CSS variables specification](https://www.w3.org/TR/css-variables-1/) is "only" at the Candidate Recommendation stage (since 3 december 2015), but still...)

**Comment by Hexstream** [comment]
Thanks for fixing but the validator instance at https://jigsaw.w3.org/css-validator/ doesn't seem to have been updated yet?... ([Example](https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fwww.hexstreamsoft.com%2F))

**Comment by implico** [comment]
Is it going to be fixed?

**Comment by svgeesus** [comment]
Is it going to be fixed?

https://github.com/w3c/specberus/issues/1030

**Comment by ylafon** [comment]
See https://github.com/w3c/css-validator/pull/173 those are not validated but should not generate errors.

**Comment by ylafon** [comment]
See #316

**Comment by ylafon** [comment]
See #324 This is probably the best we can do so far for static checks for dynamic values.
I am closing this, but there might be some new issues relative to implementation of variables that will emerge.
