### ISSUE TITLE
Parse error on "font: 0 Ahem" used by CSS 2.1 test suite

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#115]
There’s some odd behaviour parsing the font: shorthand using different variants of zero (0, 0%, 0pt, 0.0) for font size, and a value error on "font: 0 Ahem" which some CSS 2.1 test suite files depend on being valid

div { font: 0 Arial; }
Value Error : font 0 is not a font-weight value : 0 Arial

div { font: 0.0 Arial; }
Value Error : font Invalid RGB function : 0.0 Arial

div { font: 0pt Arial; }
Congratulations! No Error Found.

div { font: 0% Arial; }
Congratulations! No Error Found.

Chrome treats font: 0 Arial; as font: 0px Arial; and some of the CSS 2.1 test suite depends on this happening. For example, these tests check that font: 0 Ahem; is overridden by a subsequent font: inherit:

http://test.csswg.org/suites/css2.1/20110323/html4/font-039.htm
http://test.csswg.org/suites/css2.1/20110323/html4/font-040.htm
http://test.csswg.org/suites/css2.1/20110323/html4/font-041.htm
http://test.csswg.org/suites/css2.1/20110323/html4/font-042.htm
http://test.csswg.org/suites/css2.1/20110323/html4/font-043.htm

There's a potential ambiguity in the CSS grammar for the font: shorthand since font-weight allows an integer font-weight and 0 also is a legal font-size value (but no other integer is a legal font-size). In CSS 3 Fonts this is resolved because font-weight numeric values are restricted to the integers 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900. In CSS 4 font-weight values are numbers greater than 0 and less than 1000, and all other values are treated as parse errors (which also resolves the ambiguity)

https://www.w3.org/TR/css-fonts-3/#propdef-font
https://www.w3.org/TR/css-fonts-4/#font-weight-prop

In CSS 3

"font: 0 Arial" is legal and equivalent to "font: 0px Arial"
"font: 12 Arial" is illegal and the 12 could either be reported as a font-size with a missing unit, or an invalid font-weight.
"font: 1001 Arial" is illegal and the 1001 could either be reported as a font-size with a missing unit, or an invalid font-weight.

In CSS 4

"font: 0 Arial" is legal and equivalent to "font: 0px Arial"
"font: 12 Arial" is legal, and equivalent to font-weight:12 font-family:Arial
"font: 1001 Arial" is illegal and the 1001 could either be reported as a font-size with a missing unit, or an invalid font-weight.

**Comment by ylafon** [comment]
This should be fixed by commit e1338a5
