### ISSUE TITLE
Parse error in CSS 2.1 test for escaped url() functional notation

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#116]
This CSS 2.1 test file checks that URL() functional notation escapes like U\r\4c ("green.png"); are legal:
http://test.csswg.org/suites/css2.1/20110323/html4/uri-015.htm
but the CSS validator reports a parse error on this file

Allowing URL escaping was documented in this errata
https://www.w3.org/Style/css2-updates/REC-CSS2-20110607-errata.html#s.4.1.1a

**Comment by ylafon** [comment]
So doing it properly is pushing JavaCC to its limit, which is the size of generated code. Will have to do a workaround...

**Comment by ylafon** [comment]
Fixed by #349
