### ISSUE TITLE
Error reported for multiple text-decoration styles in CSS 2.1 test suite

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#117]
This CSS 2.1 test suite file checks that multiple text-decoration styles are valid:
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-021.htm

The CSS validator reports this as invalid:
Value Error : text-decoration overline is not a color value : underline blink overline

The same issue is reported in a number of other test suite files:

http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-022.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-027.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-028.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-033.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-034.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-042.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-044.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-045.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-046.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-048.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-050.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-051.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-052.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-054.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-056.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-057.htm
http://test.csswg.org/suites/css2.1/20110323/html4/text-decoration-058.htm

**Comment by ylafon** [comment]
Note that using the CSS2.1 Profile, all those URLs are considered as valid.
So the issue in with the CSS3 Profile that should be fixed and updated according to https://www.w3.org/TR/2013/CR-css-text-decor-3-20130801/#text-decoration-property

**Comment by ylafon** [comment]
Looks like this was not closed as it should.
