### ISSUE TITLE
WebUI: protocol-less URI issue

### ISSUE THREAD

**Issue by XhmikosR** [w3c/css-validator#144]
If one adds a protocol-less URI to validate, the result assumes it's just `http`.

I don't know if the checker follows the https redirect or just scans the http domain. If it's the latter I guess it's wrong. If it's the former, then the UI should reflect the redirect change.

**Comment by ylafon** [comment]
The validator follows redirects, if presents. 
The markup validator seems to infer 'http' as the default protocol as well for protocol-less URIs, so we are consistant (but we could change consistently in the future)

**Comment by XhmikosR** [comment]
Sorry but how is that good UX? It shoes http but it's using https you are
saying. I, as an end user don't see that.

**Comment by XhmikosR** [comment]
@sideshowbarker: can you take a stab at fixing this? See my above comment.
