### ISSUE TITLE
Question about white space in at-media rule

### ISSUE THREAD

**Issue by CecilWard** [w3c/css-validator#148]
The W3C CSS validator rejects this fragment with an error and no details 
  @media screen and(min-device-width:1024px)and(max-device-width:1366px) {}
but is happy with the familiar whitespace 
  @media screen and (min-device-width:1024px) and (max-device-width:1366px) {}

Is the whitespace really required? (Whitespace distribution was always something I submitted many complaints about concerning CSS 2.1.)

I can't make heads nor tails from the latest spec it's so verbose and perhaps insufficiently formal.

**Comment by ylafon** [comment]
The current code indeed mandate at least one space after "and" `<AND> ( <S> )+`
Will check if the spec changed.

**Comment by ylafon** [comment]
From https://www.w3.org/TR/2012/REC-css3-mediaqueries-20120619/#syntax

> The following is an malformed media query because having no space between ‘and’ and the expression is not allowed. (That is reserved for the functional notation syntax.)
> 
> @​​media all and(color) { … }

Note that `@​media screen and (min-device-width:1024px)and (max-device-width:1366px) {}` validates

**Comment by ylafon** [comment]
There is still the issue about reporting properly what is the issue, but it's a more general (and difficult) one.
