### ISSUE TITLE
Wrong references with parameter xhtml

### ISSUE THREAD

**Issue by ikabod** [w3c/css-validator#156]
If you use for example this url to validate by direct input:

https://jigsaw.w3.org/css-validator/validator/?output=xhtml&text=body{color:red!important}

it works fine, but there are some references in the html code wrong:

link xmlns="http://www.w3.org/1999/xhtml" type="text/css" rel="stylesheet" href="style/base.css" /
link xmlns="http://www.w3.org/1999/xhtml" type="text/css" rel="stylesheet" href="style/results.css" /

should be:

link xmlns="http://www.w3.org/1999/xhtml" type="text/css" rel="stylesheet" href="../style/base.css" /
link xmlns="http://www.w3.org/1999/xhtml" type="text/css" rel="stylesheet" href="../style/results.css" /

The same problem is with the images.

**Comment by ylafon** [comment]
In fact the calling URL is wrong, it should be `validator?output=...` instead of `validator/?output=...`

**Comment by ikabod** [comment]
Ahh, ok, sorry, that was my fault. On my own server I use this slash before a query - just a habit.

**Comment by ylafon** [comment]
NP
