### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by ikabod** [w3c/css-validator#159]
https://jigsaw.w3.org/css-validator/validator?output=xhtml&text=body{min-width:50pp}

should be "Unbekannte Dimension"

If there is a list with the error messages, I can correct them (I am German native speaker).

**Comment by ylafon** [comment]
There is a big table for all translation at https://jigsaw.w3.org/css-validator/translations.html
You can also see the original in english at https://raw.githubusercontent.com/w3c/css-validator/master/org/w3c/css/util/Messages.properties.en
and the german translation (with some messages not yet translated) at https://raw.githubusercontent.com/w3c/css-validator/master/org/w3c/css/util/Messages.properties.de

**Comment by ikabod** [comment]
Ok, thank you. I corrected the file and translated the missing translations. I renamed the file, since .de-Files cannot be uploaded here:

[Messages.properties.de.txt](https://github.com/w3c/css-validator/files/1662701/Messages.properties.de.txt)

**Comment by ikabod** [comment]
You did not respond yet. Is something wrong with the file?

**Comment by ylafon** [comment]
No it's just that I don't have time right now, I'll fold in the changes early next week.

**Comment by ikabod** [comment]
Ok, thank you.

**Comment by ikabod** [comment]
Please do not forget this.

**Comment by ylafon** [comment]
In production now. Thanks.

**Comment by ikabod** [comment]
Thanks too.
