### ISSUE TITLE
Not working on IE11 or Edge

### ISSUE THREAD

**Issue by IanC311** [w3c/css-validator#162]
Validation service has recently stopped working on IE11 and Edge.  A file can be selected using the browse button, but then the check button does nothing.  Adding the site to the compatibility view list in IE allows it to work.

**Comment by sideshowbarker** [comment]
Are any error messages reported in the IE11/Edge devtools console?

**Comment by sideshowbarker** [comment]
I believe the change in af3f301 fixes this, but I don’t have IE or Edge to test with, so I’m not sure
