### ISSUE TITLE
Unknown error java.lang.Exception thrown for some @charset issues

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#187]
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-utf16-be-003.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-16BE and UTF-16 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-utf16-le-003.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-16LE and UTF-16 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-002.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset Shift_JIS and windows-1252 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-042.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-8 and UTF-16BE 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-043.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-16LE and UTF-8 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-044.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-32BE and UTF-16BE 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-045.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-16LE and UTF-16BE 
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-046.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-16BE and UTF-16LE 
http://test.csswg.org/suites/css2.1/20110323/html4/at-charset-061.htm Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-8 and ISO-8859-1 
http://test.csswg.org/suites/css2.1/20110323/html4/support/bom-charset15.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-8 and iso-8859-15 
http://test.csswg.org/suites/css2.1/20110323/html4/support/bom-charset15.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset UTF-8 and iso-8859-15 
http://test.csswg.org/suites/css2.1/20110323/html4/support/http1-charset8.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset ISO-8859-1 and utf-8 
http://test.csswg.org/suites/css2.1/20110323/html4/support/http1-charset8.css Unknown error java.lang.Exception: Conflicting charset definition between network and @charset ISO-8859-1 and utf-8

**Comment by ylafon** [comment]
Fixed and in production.
Thanks!
