### ISSUE TITLE
Why is the rule ".d { font: n }" valid?

### ISSUE THREAD

**Issue by smuehlst** [w3c/css-validator#192]
I submitted the following CSS rule to the [CSS Validation Service](https://jigsaw.w3.org/css-validator/) for validation against "CSS level 2":

    .d { font: n }

This is validated as correct CSS 2. I do not understand how this CSS rule can be constructed according to the section  ["Shorthand font property: the 'font' property" in the CSS 2 Specification](https://www.w3.org/TR/CSS2/fonts.html#font-shorthand).

The syntax of the "font" property is this:

    Value: [ [ <'font-style'> || <'font-variant'> || <'font-weight'> ]? <'font-size'> [ / <'line-height'> ]? <'font-family'> ] | caption | icon | menu | message-box | small-caption | status-bar | inherit

"n" is none of the keywords that can occur, so the only syntax element that could apply is the 'font-family'. But if that would be the case, also 'font-size' would have to present.

**Comment by ylafon** [comment]
It is currently parsed as a font-family, but there should be a font-size before. So yes, it is a bug.
