### ISSUE TITLE
CSS 193 errors in my blog https://www.govtjobalertindia.com Help to fix me

### ISSUE THREAD

**Issue by shashikumargupta** [w3c/css-validator#202]
Error: Line 1 .contact-form-widget
Value Error : height (nullvisudet.html#propdef-height) only “0” can be a “unit”. You must put a unit after your number :
Error: Line 1 .contact-form-button
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button:hover, .contact-form-button.hover
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button:hover, .contact-form-button.hover
“0” is not a “transition” value :
Error: Line 1 .contact-form-button-submit
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button-submit:hover
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button-submit
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button-submit:hover
Value Error : background-image (nullcolors.html#propdef-background-image) The first argument to the “linear-gradient” function should be “to top”, not “top”
Error: Line 1 .contact-form-button.disabled, .contact-form-button.disabled:hover, .contact-form-button.disabled:active
Property “pointer-events” doesn't exist :
Error: Line 1 .label-size-1
“alpha(80)” is not a “filter” value :
Error: Line 1 .label-size-2
“alpha(90)” is not a “filter” value :
Error: Line 1 .blogger-logo, .svg-icon-24.blogger-logo
Property “fill” doesn't exist :
Error: Line 1 .share-buttons .svg-icon-24, .centered-bottom .share-buttons .svg-icon-24
Property “fill” doesn't exist :
Error: Line 1 .share-buttons li .platform-sharing-text
Parse Error
Error: Line 1 
Parse Error
Error: Line 1 .backlink-toggle-zippy
Value Error : cursor (nullui.html#propdef-cursor) “hand” is not a “cursor” value :
Error: Line 1 
Unknown pseudo-element or pseudo-class “::root”
Error: Line 1 
Unknown pseudo-element or pseudo-class “::root”
Error: Line 1 
Unknown pseudo-element or pseudo-class “::root”
Error: Line 1 .widget .widget-item-control a img
Value Error : padding (nullbox.html#propdef-padding) “none” is not a “padding” value :

https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

Error: Line 4 .fa
Property “text-rendering” doesn't exist :

https://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css

Error: Line 18 .fa
Property “text-rendering” doesn't exist :

https://www.govtjobalertindia.com

Error: Line 47 #header h1, #header h2
Property “font-varient” doesn't exist. The closest matching property name is “font-variant” :
Error: Line 50 #header p.description
Property “disply” doesn't exist. The closest matching property name is “display” :
Error: Line 74 .menu li:hover::after, .menu li.home::after
Parse Error
Error: Line 77 .menu ul:after
Property “pointer-events” doesn't exist :
Error: Line 85 .menu ul ul:after
Property “pointer-events” doesn't exist :
Error: Line 103 .post-body
Value Error : text-transform (nulltext.html#propdef-text-transform) “auto” is not a “text-transform” value :
Error: Line 116 .blog-cent p
Value Error : height (nullvisudet.html#propdef-height) Parse Error
Error: Line 216 #comments h3
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 216 #comments h3
Parse Error
Error: Line 216 #comments h3
Parse Error
Error: Line 218 #comments .click-comment
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 218 #comments .click-comment
Parse Error
Error: Line 218 #comments .click-comment
Parse Error
Error: Line 225 .comment_name a
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 225 .comment_name a
Parse Error
Error: Line 225 .comment_name a
Parse Error
Error: Line 228 .comment_admin .comment_name
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 228 .comment_admin .comment_name
Parse Error
Error: Line 228 .comment_admin .comment_name
Parse Error
Error: Line 230 .comment_name
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 230 .comment_name
Parse Error
Error: Line 230 .comment_name
Parse Error
Error: Line 236 .comment-delete
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 236 .comment-delete
Parse Error
Error: Line 239 .comment_body p
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 239 .comment_body p
Parse Error
Error: Line 239 .comment_body p
Parse Error
Error: Line 241 .comment_body p:before, .comment_body p:after
Value Error : content (nullgenerate.html#propdef-content) Parse Error
Error: Line 241 .comment_body p:before, .comment_body p:after
Parse Error
Error: Line 241 .comment_body p:before, .comment_body p:after
Property “pointer-events” doesn't exist :
Error: Line 253 .comment_reply
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 253 .comment_reply
Parse Error
Error: Line 267 .deleted-comment
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 267 .deleted-comment
Parse Error
Error: Line 267 .deleted-comment
Parse Error
Error: Line 275 .comment_admin .comment_author_flag
Value Error : font-family (nullfonts.html#propdef-font-family) Parse Error
Error: Line 275 .comment_admin .comment_author_flag
Parse Error
Error: Line 784 
Property “mso-padding-alt” doesn't exist :
Error: Line 784 
Property “mso-yfti-tbllook” doesn't exist :
Error: Line 786 
Property “mso-yfti-firstrow” doesn't exist :
Error: Line 786 
Property “mso-yfti-irow” doesn't exist :
Error: Line 787 
Property “mso-border-alt” doesn't exist :
Error: Line 790 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 790 
Property “mso-border-right-alt” doesn't exist :
Error: Line 790 
Property “mso-border-top-alt” doesn't exist :
Error: Line 793 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 793 
Property “mso-border-right-alt” doesn't exist :
Error: Line 793 
Property “mso-border-top-alt” doesn't exist :
Error: Line 797 
Property “mso-yfti-irow” doesn't exist :
Error: Line 798 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 798 
Property “mso-border-left-alt” doesn't exist :
Error: Line 798 
Property “mso-border-right-alt” doesn't exist :
Error: Line 801 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 801 
Property “mso-border-right-alt” doesn't exist :
Error: Line 804 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 804 
Property “mso-border-right-alt” doesn't exist :
Error: Line 808 
Property “mso-yfti-irow” doesn't exist :
Error: Line 809 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 809 
Property “mso-border-left-alt” doesn't exist :
Error: Line 809 
Property “mso-border-right-alt” doesn't exist :
Error: Line 812 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 812 
Property “mso-border-right-alt” doesn't exist :
Error: Line 815 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 815 
Property “mso-border-right-alt” doesn't exist :
Error: Line 819 
Property “mso-yfti-irow” doesn't exist :
Error: Line 819 
Property “mso-yfti-lastrow” doesn't exist :
Error: Line 820 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 820 
Property “mso-border-left-alt” doesn't exist :
Error: Line 820 
Property “mso-border-right-alt” doesn't exist :
Error: Line 823 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 823 
Property “mso-border-right-alt” doesn't exist :
Error: Line 826 
Property “mso-border-bottom-alt” doesn't exist :
Error: Line 826 
Property “mso-border-right-alt” doesn't exist :
Error: Line 888 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 888 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 890 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 890 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 892 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 892 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 1052 
Property “mso-list” doesn't exist :
Error: Line 1052 
Property “tab-stops” doesn't exist :
Error: Line 1054 
Property “mso-list” doesn't exist :
Error: Line 1054 
Property “tab-stops” doesn't exist :
Error: Line 1056 
Property “mso-list” doesn't exist :
Error: Line 1056 
Property “tab-stops” doesn't exist :
Error: Line 1063 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 1063 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 1065 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 1065 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 1067 
Property “mso-fareast-font-family” doesn't exist :
Error: Line 1067 
Property “mso-fareast-theme-font” doesn't exist :
Error: Line 1269 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1269 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1269 
Property “mso-spacerun” doesn't exist :
Error: Line 1269 
Property “mso-spacerun” doesn't exist :
Error: Line 1269 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1441 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1442 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1659 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1660 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1660 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1670 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1679 
Property “mso-list” doesn't exist :
Error: Line 1679 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1679 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1679 
Property “tab-stops” doesn't exist :
Error: Line 1682 
Property “mso-list” doesn't exist :
Error: Line 1682 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1682 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1682 
Property “tab-stops” doesn't exist :
Error: Line 1684 
Property “mso-list” doesn't exist :
Error: Line 1684 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1684 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1684 
Property “tab-stops” doesn't exist :
Error: Line 1687 
Property “mso-list” doesn't exist :
Error: Line 1687 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1687 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1687 
Property “tab-stops” doesn't exist :
Error: Line 1689 
Property “mso-list” doesn't exist :
Error: Line 1689 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1689 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1689 
Property “tab-stops” doesn't exist :
Error: Line 1693 
Property “mso-list” doesn't exist :
Error: Line 1693 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1693 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1693 
Property “tab-stops” doesn't exist :
Error: Line 1695 
Property “mso-list” doesn't exist :
Error: Line 1695 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1695 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1695 
Property “tab-stops” doesn't exist :
Error: Line 1698 
Property “mso-list” doesn't exist :
Error: Line 1698 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1698 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1698 
Property “tab-stops” doesn't exist :
Error: Line 1700 
Property “mso-list” doesn't exist :
Error: Line 1700 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1700 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1700 
Property “tab-stops” doesn't exist :
Error: Line 1703 
Property “mso-list” doesn't exist :
Error: Line 1703 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1703 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1703 
Property “tab-stops” doesn't exist :
Error: Line 1705 
Property “mso-list” doesn't exist :
Error: Line 1705 
Property “mso-margin-bottom-alt” doesn't exist :
Error: Line 1705 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1705 
Property “tab-stops” doesn't exist :
Error: Line 1875 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1876 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1978 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 1981 
Property “mso-list” doesn't exist :
Error: Line 1981 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1981 
Property “tab-stops” doesn't exist :
Error: Line 1982 
Property “mso-list” doesn't exist :
Error: Line 1984 
Property “mso-list” doesn't exist :
Error: Line 1984 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1984 
Property “tab-stops” doesn't exist :
Error: Line 1985 
Property “mso-list” doesn't exist :
Error: Line 1987 
Property “mso-list” doesn't exist :
Error: Line 1987 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1987 
Property “tab-stops” doesn't exist :
Error: Line 1991 
Property “mso-list” doesn't exist :
Error: Line 1991 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 1991 
Property “tab-stops” doesn't exist :
Error: Line 1992 
Property “mso-list” doesn't exist :
Error: Line 1994 
Property “mso-margin-top-alt” doesn't exist :
Error: Line 2104 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 2104 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 2104 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 2104 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 2107 
Property “mso-bidi-font-weight” doesn't exist :
Error: Line 2108 
Property “mso-bidi-font-weight” doesn't exist :

180 Warnings Found

https://www.govtjobalertindia.com

Warning: Line 32 
“-moz-box-sizing” is an unknown vendor extension
Warning: Line 34 
“-moz-box-sizing” is an unknown vendor extension
Warning: Line 34 
“-webkit-box-sizing” is an unknown vendor extension
Warning: Line 56 
“-o-transition” is an unknown vendor extension
Warning: Line 56 
“-webkit-transition” is an unknown vendor extension
Warning: Line 56 
“-moz-transition” is an unknown vendor extension
Warning: Line 56 
“-webkit-border-radius” is an unknown vendor extension
Warning: Line 56 
“-moz-border-radius” is an unknown vendor extension
Warning: Line 142 
“8” is out of range
Warning: Line 216 
“,sans-serif” is a CSS hack
Warning: Line 218 
“,sans-serif” is a CSS hack
Warning: Line 225 
“,sans-serif” is a CSS hack
Warning: Line 228 
“,sans-serif” is a CSS hack
Warning: Line 230 
“,sans-serif” is a CSS hack
Warning: Line 239 
“,Helvetica” is a CSS hack
Warning: Line 241 
“"” is a CSS hack
Warning: Line 267 
“,Helvetica” is a CSS hack
Warning: Line 321 
“-webkit-min-device-pixel-ratio” is an unknown vendor extension
Warning: Line 787 
The value “windowtext” is deprecated
Warning: Line 790 
The value “windowtext” is deprecated
Warning: Line 793 
The value “windowtext” is deprecated
Warning: Line 798 
The value “windowtext” is deprecated
Warning: Line 801 
The value “windowtext” is deprecated
Warning: Line 801 
The value “windowtext” is deprecated
Warning: Line 804 
The value “windowtext” is deprecated
Warning: Line 804 
The value “windowtext” is deprecated
Warning: Line 809 
The value “windowtext” is deprecated
Warning: Line 812 
The value “windowtext” is deprecated
Warning: Line 812 
The value “windowtext” is deprecated
Warning: Line 815 
The value “windowtext” is deprecated
Warning: Line 815 
The value “windowtext” is deprecated
Warning: Line 820 
The value “windowtext” is deprecated
Warning: Line 823 
The value “windowtext” is deprecated
Warning: Line 823 
The value “windowtext” is deprecated
Warning: Line 826 
The value “windowtext” is deprecated
Warning: Line 826 
The value “windowtext” is deprecated
Warning: Line 925 
“-webkit-text-stroke-width” is an unknown vendor extension
Warning: Line 1675 
The value “windowtext” is deprecated
Warning: Line 1680 
The value “windowtext” is deprecated
Warning: Line 1752 
“zoom” is an unknown vendor extension
Warning: Line 1783 
Family names containing whitespace should be quoted. If quoting is omitted, any whitespace characters before and after the name are ignored and any sequence of whitespace characters inside the name is converted to a single space.
Warning: Line 1785 
Family names containing whitespace should be quoted. If quoting is omitted, any whitespace characters before and after the name are ignored and any sequence of whitespace characters inside the name is converted to a single space.

https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

Warning: Line 4 
“-webkit-font-smoothing” is an unknown vendor extension
Warning: Line 4 
“-moz-osx-font-smoothing” is an unknown vendor extension
Warning: Line 4 
“-webkit-animation” is an unknown vendor extension
Warning: Line 4 
“-webkit-animation” is an unknown vendor extension
Warning: Line 4 
Unrecognized at-rule “@-webkit-keyframes”
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=1)” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-ms-transform” is an unknown vendor extension
Warning: Line 4 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=2)” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-ms-transform” is an unknown vendor extension
Warning: Line 4 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=3)” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-ms-transform” is an unknown vendor extension
Warning: Line 4 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-ms-transform” is an unknown vendor extension
Warning: Line 4 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=2, mirror=1)” is an unknown vendor extension
Warning: Line 4 
“-webkit-transform” is an unknown vendor extension
Warning: Line 4 
“-ms-transform” is an unknown vendor extension

https://www.blogger.com/static/v1/widgets/224787869-widget_css_bundle.css

Warning: Line 1 
“-webkit-border-radius” is an unknown vendor extension
Warning: Line 1 
“-moz-border-radius” is an unknown vendor extension
Warning: Line 1 
“-webkit-transition” is an unknown vendor extension
Warning: Line 1 
“-moz-transition” is an unknown vendor extension
Warning: Line 1 
“-o-transition” is an unknown vendor extension
Warning: Line 1 
“-webkit-user-select” is an unknown vendor extension
Warning: Line 1 
“-moz-user-select” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#f5f5f5),to(#f1f1f1))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#f5f5f5,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#f5f5f5,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#f5f5f5,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#f5f5f5,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#f5f5f5',EndColorStr='#f1f1f1')” is an unknown vendor extension
Warning: Line 1 
“*min-width” is a CSS hack
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-transition” is an unknown vendor extension
Warning: Line 1 
“-o-transition” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-transition” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#f8f8f8),to(#f1f1f1))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#f8f8f8,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#f8f8f8,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#f8f8f8,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#f8f8f8,#f1f1f1)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#f8f8f8',EndColorStr='#f1f1f1')” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#777),to(#555))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#777,#555)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#777,#555)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#777,#555)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#777,#555)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#777777',EndColorStr='#555555')” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#666),to(#444))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#666,#444)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#666,#444)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#666,#444)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#666,#444)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#666666',EndColorStr='#444444')” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#4d90fe),to(#4787ed))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#4d90fe,#4787ed)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#4d90fe,#4787ed)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#4d90fe,#4787ed)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#4d90fe,#4787ed)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#4d90fe',EndColorStr='#4787ed')” is an unknown vendor extension
Warning: Line 1 
“-webkit-gradient(linear,left top,left bottom,from(#4d90fe),to(#357ae8))” is an unknown vendor extension
Warning: Line 1 
“-webkit-linear-gradient(top,#4d90fe,#357ae8)” is an unknown vendor extension
Warning: Line 1 
“-moz-linear-gradient(top,#4d90fe,#357ae8)” is an unknown vendor extension
Warning: Line 1 
“-ms-linear-gradient(top,#4d90fe,#357ae8)” is an unknown vendor extension
Warning: Line 1 
“-o-linear-gradient(top,#4d90fe,#357ae8)” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.gradient(startColorStr='#4d90fe',EndColorStr='#357ae8')” is an unknown vendor extension
Warning: Line 1 
“-ms-filter” is an unknown vendor extension
Warning: Line 1 
“alpha(opacity=50)” is an unknown vendor extension
Warning: Line 1 
“::-webkit-input-placeholder” is an unknown vendor extended pseudo-element
Warning: Line 1 
“:-moz-placeholder” is an unknown vendor extended pseudo-class
Warning: Line 1 
“-moz-border-radius” is an unknown vendor extension
Warning: Line 1 
“::-ms-clear” is an unknown vendor extended pseudo-element
Warning: Line 1 
“alpha(opacity=65)” is an unknown vendor extension
Warning: Line 1 
“zoom” is an unknown vendor extension
Warning: Line 1 
“zoom” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.AlphaImageLoader(src='https://resources.blogblog.com/img/widgets/s_top.png',sizingMethod='crop')” is an unknown vendor extension
Warning: Line 1 
“progid:DXImageTransform.Microsoft.AlphaImageLoader(src='https://resources.blogblog.com/img/widgets/s_bottom.png',sizingMethod='crop')” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-sizing” is an unknown vendor extension
Warning: Line 1 
“-moz-box-sizing” is an unknown vendor extension
Warning: Line 1 
“-ms-box-sizing” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-ms-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-ms-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-border-radius” is an unknown vendor extension
Warning: Line 1 
“-moz-border-radius” is an unknown vendor extension
Warning: Line 1 
“-ms-border-radius” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-ms-box-shadow” is an unknown vendor extension
Warning: Line 1 
“_font-size” is an unknown vendor extension
Warning: Line 1 
“alpha(opacity=40)” is an unknown vendor extension
Warning: Line 1 
“-moz-opacity” is an unknown vendor extension
Warning: Line 1 
“alpha(opacity=30)” is an unknown vendor extension
Warning: Line 1 
“-moz-opacity” is an unknown vendor extension
Warning: Line 1 
“_width” is an unknown vendor extension
Warning: Line 1 
“-ms-interpolation-mode” is an unknown vendor extension
Warning: Line 1 
“-moz-inline-box” is an unknown vendor extension
Warning: Line 1 
“-moz-box-orient” is an unknown vendor extension
Warning: Line 1 
“-webkit-border-radius” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-sizing” is an unknown vendor extension
Warning: Line 1 
“-moz-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-webkit-box-shadow” is an unknown vendor extension
Warning: Line 1 
“-ie-box-shadow” is an unknown vendor extension

https://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css

Warning: Line 19 
“-webkit-font-smoothing” is an unknown vendor extension
Warning: Line 20 
“-moz-osx-font-smoothing” is an unknown vendor extension
Warning: Line 80 
“-webkit-animation” is an unknown vendor extension
Warning: Line 83 
Unrecognized at-rule “@-webkit-keyframes”
Warning: Line 95 
“-webkit-transform” is an unknown vendor extension
Warning: Line 99 
“-webkit-transform” is an unknown vendor extension
Warning: Line 104 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=1)” is an unknown vendor extension
Warning: Line 105 
“-webkit-transform” is an unknown vendor extension
Warning: Line 106 
“-ms-transform” is an unknown vendor extension
Warning: Line 110 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=2)” is an unknown vendor extension
Warning: Line 111 
“-webkit-transform” is an unknown vendor extension
Warning: Line 112 
“-ms-transform” is an unknown vendor extension
Warning: Line 116 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=3)” is an unknown vendor extension
Warning: Line 117 
“-webkit-transform” is an unknown vendor extension
Warning: Line 118 
“-ms-transform” is an unknown vendor extension
Warning: Line 122 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)” is an unknown vendor extension
Warning: Line 123 
“-webkit-transform” is an unknown vendor extension
Warning: Line 124 
“-ms-transform” is an unknown vendor extension
Warning: Line 128 
“progid:DXImageTransform.Microsoft.BasicImage(rotation=2, mirror=1)” is an unknown vendor extension
Warning: Line 129 
“-webkit-transform” is an unknown vendor extension
Warning: Line 130 
“-ms-transform” is an unknown vendor extension

**Comment by ylafon** [comment]
Unfortunately, we cannot fix all CSS pages for people. I recommend asking on the public mailing list www-validator-css@w3.org or other specialised fora.
