### ISSUE TITLE
Support css-align-3 (was: Bring 'justify-self' and 'justify-content' checking up-to-date with current spec)

### ISSUE THREAD

**Issue by XhmikosR** [w3c/css-validator#204]
Originally reported on https://github.com/validator/validator/issues/690 (_“'justify-content: space-evenly' is valid CSS”_)

Also, I'm seeing a similar issue in a project of mine, but I assume it's the same problem. `Property justify-self doesn't exist : flex-end `

**Comment by ylafon** [comment]
justify-content is currently implemented using the flex box specification only, needs to add css-align-3, so editing the issue title accordingly.

**Comment by ylafon** [comment]
tracked in the [yl-css-align-3](https://github.com/w3c/css-validator/tree/yl-css-align-3) branch.

**Comment by oliviertassinari** [comment]
Awesome!

**Comment by XhmikosR** [comment]
Thanks!
