### ISSUE TITLE
font-family property not recognized in @​page

### ISSUE THREAD

**Issue by ylafon** [w3c/css-validator#207]
reported by @sideshowbarker 

@​page { font-family: "example" } triggers: 
> Value Error : font-family Property font-family doesn't exist in CSS Level 3 + SVG but exists in [css1, css2, css21, css3] :

Which is obviously wrong. The issue is that @​page has specific properties and also generic ones. It needs to be allowed.

**Comment by dd8** [comment]
I think this fix is now flagging invalid page properties as valid

Only a restricted set of properties are allowed:
https://drafts.csswg.org/css-page-3/#page-properties

```
/* should be valid */
@page { direction: rtl; } 
@page { font-family: "example"; } 

/* invalid - in CSS 2.1 but not allowed in @page */
@page { cursor: pointer; } 
@page { volume: loud; } 

/* undefined behaviour - not in CSS 2.1 */
@page { animation: 3s slidein; } 
@page { scroll-behavior: smooth; }
@page { transition: all 1s ease-out; }
```

**Comment by ylafon** [comment]
Indeed, I will amend the list and work on the missing @​page specific properties once I get a stable reference for it (See followup on your w3c/csswg-drafts#3156 ).
Thanks

**Comment by dd8** [comment]
If you do get a stable spec reference, it might be worth re-ordering the @page properties to match the order in the spec (to make it easier to spot missing properties)

There are also some additional properties allowed in page margin boxes like @top-left, but not in @page: unicode-bidi, content, vertical-align, z-index
https://drafts.csswg.org/css-page-3/#margin-property-list

**Comment by ylafon** [comment]
The @​page properties are now in a separate property file, to make things easier.

**Comment by ylafon** [comment]
@​page parsing has been redone per https://www.w3.org/TR/2018/WD-css-page-3-20181018/#syntax-page-selector there are still issues regarding printing of parsed @​page rules, but I will close this specific issue.
