### ISSUE TITLE
CSS Level 3: Wrong warning for incompatible attribute values

### ISSUE THREAD

**Issue by raducoravu** [w3c/css-validator#210]
I have this CSS selector:

    *[class~='abc'][class~='def'] {
    }

and I get this validation warning:

    (Level : 0) “[class~="abc"]” and “[class~="def"]” are incompatible

In my opinion the warning should not be given because the @class attribute value on an element can have multiple space separted values like:

    <span class="abc def"/>

**Comment by sideshowbarker** [comment]
I can’t reproduce that error from the checker with just `*[class~='abc'][class~='def'] {}` as input:

https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fcss%2C%252A%255Bclass~%253D%2527abc%2527%255D%255Bclass~%253D%2527def%2527%255D%2520%257B%257D%250D%250A#textarea

Do you have a test document or URL that can be used to reproduce the error?

**Comment by sideshowbarker** [comment]
Ah, ignore my previous comment — I thought this issue had been reported against the CSS-checking feature of the HTML checker … 😌

**Comment by ylafon** [comment]
Thanks for reporting it!
