### ISSUE TITLE
Supporting css3svg as a profile parameter value

### ISSUE THREAD

**Issue by ArunSahadeo** [w3c/css-validator#217]
Hi,

I have written a Vim plugin for validation of HTML and CSS (https://github.com/ArunSahadeo/Webval). Someone was using my plugin and was enquiring about supporting `css3svg` as a profile parameter value (as seen in https://github.com/ArunSahadeo/Webval/issues/1).

Is this doable?

I am not familiar with the infrastructure of this project, so if you lack time, I could take a look into it.

**Comment by ylafon** [comment]
`css3svg` is indeed a supported profile. Do you have a specific issue using it ?

**Comment by ylafon** [comment]
I am wondering which server is being called...

**Comment by ylafon** [comment]
Closing as it is not a css-validator bug.
