### ISSUE TITLE
Current release is out of date (issues e.g. with justify-self)

### ISSUE THREAD

**Issue by dfht** [w3c/css-validator#223]
The current 'full release' (on the GitHub 'releases' tab) with all the extra third party dependencies  is out of date.
For example, it has issues like it flags perfectly valid CSS3 flex-box related rules as errors.
An example is the justify-self rule, which is flagged as invalid in this version.

**Comment by ylafon** [comment]
A new release has been made, note that this will not be a frequent thing, expect once a year, otherwise the master branch should be stable and readily usable.
