### ISSUE TITLE
Error shows normal is not a font-feature-settings value? 🤔

### ISSUE THREAD

**Issue by willowcheng** [w3c/css-validator#224]
By checking home page of shopify.com, it shows the [result](https://jigsaw.w3.org/css-validator/validator?uri=www.shopify.com&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) that `normal` is not a `font-feature-settings` value by CSS validator.

Accordion to `font-feature-settings` CSS documentation, it mentions `normal` is an available value which is also the initial value: https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#propdef-font-feature-settings. 🤔

Not sure if it's the right place to ask this, point me out if there is a better place to ask about it. 😅

**Comment by ylafon** [comment]
In fact it is more a bug that a specification change as it was present in the definition used to create the code.
