### ISSUE TITLE
I18n tags are missing in Messages.properties files

### ISSUE THREAD

**Issue by AdrianSorop** [w3c/css-validator#226]
I've noticed that are some missing properties in the message files from German, like: _error.noexistence-typo_ is not defined in German, but exists in English/French..

**Comment by AdrianSorop** [comment]
As far as I know, here are the missing keys, for each supported language:

[MissingMessages_properties_bg.txt](https://github.com/w3c/css-validator/files/2983452/MissingMessages_properties_bg.txt)
[MissingMessages_properties_cs.txt](https://github.com/w3c/css-validator/files/2983453/MissingMessages_properties_cs.txt)
[MissingMessages_properties_de.txt](https://github.com/w3c/css-validator/files/2983454/MissingMessages_properties_de.txt)
[MissingMessages_properties_el.txt](https://github.com/w3c/css-validator/files/2983455/MissingMessages_properties_el.txt)
[MissingMessages_properties_es.txt](https://github.com/w3c/css-validator/files/2983456/MissingMessages_properties_es.txt)
[MissingMessages_properties_fa.txt](https://github.com/w3c/css-validator/files/2983457/MissingMessages_properties_fa.txt)
[MissingMessages_properties_hi.txt](https://github.com/w3c/css-validator/files/2983458/MissingMessages_properties_hi.txt)
[MissingMessages_properties_hu.txt](https://github.com/w3c/css-validator/files/2983459/MissingMessages_properties_hu.txt)
[MissingMessages_properties_it.txt](https://github.com/w3c/css-validator/files/2983460/MissingMessages_properties_it.txt)
[MissingMessages_properties_ja.txt](https://github.com/w3c/css-validator/files/2983461/MissingMessages_properties_ja.txt)
[MissingMessages_properties_ko.txt](https://github.com/w3c/css-validator/files/2983462/MissingMessages_properties_ko.txt)
[MissingMessages_properties_nl.txt](https://github.com/w3c/css-validator/files/2983463/MissingMessages_properties_nl.txt)
[MissingMessages_properties_pl-PL.txt](https://github.com/w3c/css-validator/files/2983464/MissingMessages_properties_pl-PL.txt)
[MissingMessages_properties_pt-BR.txt](https://github.com/w3c/css-validator/files/2983465/MissingMessages_properties_pt-BR.txt)
[MissingMessages_properties_ro.txt](https://github.com/w3c/css-validator/files/2983466/MissingMessages_properties_ro.txt)
[MissingMessages_properties_ru.txt](https://github.com/w3c/css-validator/files/2983467/MissingMessages_properties_ru.txt)
[MissingMessages_properties_sv.txt](https://github.com/w3c/css-validator/files/2983468/MissingMessages_properties_sv.txt)
[MissingMessages_properties_uk.txt](https://github.com/w3c/css-validator/files/2983469/MissingMessages_properties_uk.txt)
[MissingMessages_properties_zh-cn.txt](https://github.com/w3c/css-validator/files/2983470/MissingMessages_properties_zh-cn.txt)

**Comment by ylafon** [comment]
Yes, it default to the english version in that case. 
It is tracked there: https://jigsaw.w3.org/css-validator/translations.html
and translations are welcome.
