### ISSUE TITLE
Unterminated comments are no longer an error in css-syntax-3

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#229]
The change is documented here https://www.w3.org/TR/css-syntax-3/#changes-css21

> Tokenization does not emit COMMENT or BAD_COMMENT tokens anymore.
> BAD_COMMENT is now considered the same as a normal token (not an error).

And the parsing algorithm says `/*` can be terminated by `*/` or EOF
https://www.w3.org/TR/css-syntax-3/#consume-a-token

So this test case should not generate errors in a CSS validator:
http://test.csswg.org/suites/css21_dev/20110323/html4/comments-003.htm

**Comment by ylafon** [comment]
Hum, changing the tokenizer for this while retaining CSS2 compatibility will be tricky.

**Comment by dd8** [comment]
Might be possible to do it with JavaCC using lexical states:
https://javacc.org/tutorials/tokenmanager

In Lex/Flex it would be done something like this

<INITIAL>"/*"  { if ( isCss3 ) BEGIN(COMMENT_CSS3); else BEGIN(COMMENT_CSS2); }
<COMMENT_CSS2>"*/" {   BEGIN(INITIAL); return Token::Comment }
<COMMENT_CSS2>EOF {   BEGIN(INITIAL); return Token::BadComment }
<COMMENT_CSS2>. {  /* discard characters inside comments */  }
<COMMENT_CSS3>"*/" { BEGIN(INITIAL); /* discard comments */  }
<COMMENT_CSS3>EOF {  BEGIN(INITIAL);  /* discard comments */  }
<COMMENT_CSS3>. {  /* discard characters inside comments */  }

There's also a bunch of changes in CSS3 regarding error recovery for unmatched '{' and '}' braces - that might affect how you implement lexical states

**Comment by dd8** [comment]
Heads up - there's a difference between the css-syntax-3 Candidate Recommendation and the Editor's Draft on handling comments

https://www.w3.org/TR/css-syntax-3/#tokenizer-algorithms 
https://drafts.csswg.org/css-syntax-3/#consume-comment

The consume-comment algorithm is not in the CR. It looks like there's an inconsistency in the Editor's Draft between consume-comment which can generate parse errors and section 12.4 which says BAD_COMMENT is no longer a parse error:
https://drafts.csswg.org/css-syntax-3/#changes-css21
