### ISSUE TITLE
Manual type selection is sometimes ignored

### ISSUE THREAD

**Issue by eligrey** [w3c/css-validator#23]
If the CSS contains the strings `"<style>"` and `"</style>"`, then the validator attempts to parse the whole file as HTML, even if type was manually selected to be CSS.

Reduced testcase:

    .test::before {
       content: "<style>";
    }
    .test::after {
       content: "</style>";
    }

Workaround: split up tags into multiple strings

    .test::before {
       content: "<" "style>";
    }
    .test::after {
       content: "<" "/style>";
    }

**Comment by sideshowbarker** [comment]
Nice catch.
