### ISSUE TITLE
`never` is being mis-reported as an invalid value of `speak`

### ISSUE THREAD

**Issue by ianthedev** [w3c/css-validator#231]
For example, the following rule:
```
div {
    speak: never;
}
```

is being mis-reported as invalid (`Value Error : speak never is not a speak value : never `).

According to the [spec](https://www.w3.org/TR/2018/NOTE-css3-speech-20180605/#speaking-props-speak), `never` is a valid value of the `speak` property.

**Comment by ylafon** [comment]
The specification you refer to is a Retired Note, meaning that it was never implemented, in that case, it defaults to CSS2 where 'never' is not a valid value (and even the implementation status of this part of CSS2 is not perfect).
