### ISSUE TITLE
Which tool can I trust, css-validator.org or jigsaw.w3.org/css-validator?

### ISSUE THREAD

**Issue by jonasjacek** [w3c/css-validator#235]
Hi, 

I am asking myself, if css-validator.org is an official W3C CSS validation tool and what the relation to jigsaw.w3.org/css-validator is. 

I am looking at some CSS custom properties right now, which are error free in css-validator.org. The same CSS trows parse errors in jigsaw.w3.org/css-validator. In both cases I used CSS level 3 for testing. 

CSS file: 
https://d33wubrfki0l68.cloudfront.net/css/b9c515aedd3c587a11b51d12c39e1c36cac8ec35/assets/css/style.css

Which tool can I trust?

**Comment by ylafon** [comment]
css-validator.org is not maintained by W3C, only https://jigsaw.w3.org/css-validator/ is.
HTH,
