### ISSUE TITLE
Allow “range context” for media features in media queries

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/css-validator#242]
https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#ref-for-range-context

> Media features with “range” type can be written in a range context, which uses standard mathematical comparison operators rather than a colon, or have their feature names prefixed with “min-” or “max-”.

https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#range-context

> The basic form, consisting of a feature name, a comparison operator, and a value, returns true if the relationship is true.
>
> > For example, `(height > 600px) (or (600px < height))` returns true if the viewport height is greater than 600px.
>
> The remaining forms, with the feature name nested between two value comparisons, returns true if both comparisons are true.
>
>> For example, `(400px < width < 1000px)` returns true if the viewport width is between 400px and 1000px (but not equal to either).

Production:

https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#mq-syntax

```
<media-feature> = ( [ <mf-plain> | <mf-boolean> | <mf-range> ] )
<mf-plain> = <mf-name> : <mf-value>
<mf-boolean> = <mf-name>
<mf-range> = <mf-name> [ '<' | '>' ]? '='? <mf-value>
           | <mf-value> [ '<' | '>' ]? '='? <mf-name>
           | <mf-value> '<' '='? <mf-name> '<' '='? <mf-value>
           | <mf-value> '>' '='? <mf-name> '>' '='? <mf-value>
```

**Comment by ylafon** [comment]
The syntax above is wrong and has been fixed in the editor's draft (<mf-name> [ '<' | '>' ]? '='? <mf-value> implies that <mf-name> <mf-value> is valid while it is not).
The parsing itself is done since 5c74971c2c172c068acfe8ed13d623ef854a2cca and the different Media Features have been adapted after that. (still in a non-master branch).
