### ISSUE TITLE
Allow  algebraic 'or' for combining of media features 

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/css-validator#243]
https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#media-conditions

> two or more media features can be chained together, such that the query is true if any of the media features are true, by placing or between them. For example, `(update: slow) or (hover: none)` matches if the device is slow to update the screen (such as an e-reader) or the primary pointing device has no hover capability, perhaps indicating that one should use a layout that displays more information rather than compactly hiding it until the user hovers.

Production:

https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#mq-syntax

```
<media-query> = <media-condition>
             | [ not | only ]? <media-type> [ and <media-condition-without-or> ]?
<media-type> = <ident>

<media-condition> = <media-not> | <media-in-parens> [ <media-and>* | <media-or>* ]
<media-condition-without-or> = <media-not> | <media-in-parens> <media-and>*
<media-not> = not <media-in-parens>
<media-and> = and <media-in-parens>
<media-or> = or <media-in-parens>
```

**Comment by ylafon** [comment]
The display is wrong (note that it was wrong with the css3-mediaqueries implementation as well), but validity check is now there since efe7dfccf1ca550e8370c3e16bbda0a486954521
(will do some tests before merging)
