### ISSUE TITLE
WSDL seems to be invalid, according to PHP

### ISSUE THREAD

**Issue by martinbean** [w3c/css-validator#245]
I’m trying to use the CSS validator programatically in a PHP script. I’m using PHP’s native `SoapClient` class. Here is my test script:

```php
$client = new SoapClient('http://www.w3.org/2005/09/css-validator.wsdl', [
    'soap_version' => SOAP_1_2,
]);
```

But this gives me the following error:

```
SOAP-ERROR: Parsing WSDL: Couldn't find <definitions> in 'http://www.w3.org/2005/09/css-validator.wsdl'
```

Is the validator using a non-standard version of SOAP?

**Comment by ylafon** [comment]
Hi, the validator is using SOAP 1.2 and the WSDL file is WSDL 2.0, both are standards, however not all toolkits support this.
