### ISSUE TITLE
Doesn't flag invalid @charset when @charset follows BOM

### ISSUE THREAD

**Issue by dd8** [w3c/css-validator#249]
The `@charset` pattern should only be recognised at position zero in the file - `@charset` anywhere else (including after the BOM) is invalid/ignored. 

https://drafts.csswg.org/css-syntax/#input-byte-stream
> If the first 1024 bytes of the stream begin with the hex sequence
> 40 63 68 61 72 73 65 74 20 22 XX* 22 3B

This file flags no errors and starts with the UTF-8 BOM:
`ef bb bf 40 63 68 61 72  73 65 74 20 22 55 54 46  |...@charset "UTF|`
http://test.csswg.org/suites/css21_dev/20110323/html4/support/at-charset-014.css

These files flag no errors and start with the UTF-16LE BOM:
`ff fe 40 00 63 00 68 00  61 00 72 00 73 00 65 00  |..@.c.h.a.r.s.e.|`
http://test.csswg.org/suites/css21_dev/20110323/html4/support/at-charset-015.css
http://test.csswg.org/suites/css21_dev/20110323/html4/support/at-charset-060.css

This file flags no errors and starts with the UTF-16BE BOM:
`fe ff 00 40 00 63 00 68  00 61 00 72 00 73 00 65  |...@.c.h.a.r.s.e|`
http://test.csswg.org/suites/css21_dev/20110323/html4/support/at-charset-016.css

**Comment by dd8** [comment]
I think there's a difference between the css-syntax-3 spec and the CSS 2.1/2.2 spec, demonstrated by this file:
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-001.css

It's served as `Content-Type: text/css; charset=shift_jis`. It also starts with a Shift_JIS byte sequence that happens to match the UTF-8 BOM (good test case)

`ef bb bf 2e e5 b9 b3 e5  92 8c 0d 0a 7b 0d 0a 20  |............{.. |`

CSS 2.1/2.2 specifies that Content-Type wins over any BOM:
https://drafts.csswg.org/css2/syndata.html#charset

css-syntax-3 uses the 'Decode' algorithm with a fallback encoding derived from Content-Type, with a note saying 
>Note: The decode algorithm gives precedence to a byte order mark (BOM), and only uses the fallback when none is found.
ttps://drafts.csswg.org/css-syntax/#input-byte-stream

This CSS 2.x algorithm gives the correct encoding for the file (Shift_JIS) and the CSS 3 algorithm gives the wrong encoding.

**Comment by tabatkins** [comment]
CSS Syntax spec editor here. This issue is correct, an @charset only works if it's the very first bytes in the file; placing one after a BOM renders it useless, and so should be flagged as an error. (It's no longer an encoding declaration, just an invalid and unrecognized rule.)

**Comment by ylafon** [comment]
It is indeed a bug due to the way BOM is used,
Will fix that.

**Comment by ylafon** [comment]
@dd8 can you check that at least for CSS3 it works as intended?
Thanks,
