### ISSUE TITLE
Please add support for the caret-shape property

### ISSUE THREAD

**Issue by frivoal** [w3c/css-validator#270]
css-ui-4 defines caret-shape https://drafts.csswg.org/css-ui-4/#caret-shape (and has done so for a few years now)

The grammar is really simple:
```
caret-shape: auto | bar | block | underscore
```

Please add support for this in the validator.

**Comment by ylafon** [comment]
Sure, do you have synthetic test results that would show current support of properties defined in css-ui-4, to help prioritize things?

**Comment by ylafon** [comment]
Closed with #271 An answer to the question above would be good for the general case, though.
