### ISSUE TITLE
CSS3 Validator Transition-duration

### ISSUE THREAD

**Issue by tolbon** [w3c/css-validator#277]
Hello it's just a question about 
transition-duration and transition-delay
This code validate simple '0' as value but W3C docs and firefox doesn't validate or talk about this.

https://github.com/w3c/css-validator/blob/53bd453f678468ada3116f00026402249a781629/org/w3c/css/properties/css3/CssTransitionDelay.java#L52
https://github.com/w3c/css-validator/blob/53bd453f678468ada3116f00026402249a781629/org/w3c/css/properties/css3/CssTransitionDuration.java#L53

Need a PR to delete this case ?

**Comment by ylafon** [comment]
You're right, css-values-3 made it clear that apart from legacy properties using Angle, unites value 0 can only be a length, if not a number, fixed now.
