### ISSUE TITLE
Another error likely due to CSS variables

### ISSUE THREAD

**Issue by martindholmes** [w3c/css-validator#279]
This probably relates to issue #111, but that ticket is locked so I'm posting here in case it helps. Given this CSS file:

~~~~~
:root {
  --leftNavWidth: 320px; }

div{
  transform: translate3d(var(--leftNavWidth), 0, 0);
}
~~~~~

the vnu.jar validator (current release) reports:

`5.51-5.51: error: CSS: “transform”: too few values for the property “transform”.`

which I'm pretty sure is wrong.

**Comment by ylafon** [comment]
fixed by #316
