### ISSUE TITLE
%s....%s in messages may render them untranslatable

### ISSUE THREAD

**Issue by r12a** [w3c/css-validator#282]
A recent email on the w3c-translators list brought up the following error message:

> “%s” is not valid, only values greater than or equal to “%s” are allowed.

This may just about be translatable, given that it's really 2 sentences rammed together. But if there are others, such as "There were %s syntax errors in file %s." you'd have a classic example of how to write unlocalisable code.  If translated into a language where the values of each %s have to be reversed (such as Japanese or German), it's not possible to indicate to the application the desired result.  The string insertion variables should be unique within the string.

For more explanation, see https://www.w3.org/International/articles/composite-messages/index.en#syntax

**Comment by xueyuanjia** [comment]
thanks 👍 @r12a for identifying and raising the issue.

**Comment by ylafon** [comment]
Yes this is a known issue since many years. Not sure it will be easy to fix.

**Comment by r12a** [comment]
Depends what programming language you're using.  In PHP you can simply rename the variables in the string itself, iirc (it's been a while).  So you'd end up with something like:

> “%s1” is not valid, only values greater than or equal to “%s2” are allowed.

or even better

> “{$number}” is not valid, only values greater than or equal to “{max_num}” are allowed.

**Comment by ylafon** [comment]
Fixed by #284 %s1 to %s9 are now available, no need to rewrite everything, as %s still works (automatic numbering in that case), but translators might use %s<number> to accommodate their needs.
