### ISSUE TITLE
Support `color-scheme`

### ISSUE THREAD

**Issue by andreubotella** [w3c/css-validator#285]
See https://github.com/whatwg/meta/issues/188#issuecomment-694245352 and the failing build in https://github.com/whatwg/encoding/pull/230

cc @sideshowbarker

**Comment by sideshowbarker** [comment]
Do you know which browsers support `color-scheme` so far? I don’t find `color-scheme` in the https://github.com/mdn/browser-compat-data data at all — and it doesn’t seem to be documented in MDN yet either.

And from looking at https://wpt.fyi/results/css/css-color-adjust/parsing/color-scheme-computed.html?label=experimental&label=master&aligned it seems that maybe `color-scheme` so far is only supported in Blink.
