### ISSUE TITLE
Add support for CSS property "backdrop-filter"

### ISSUE THREAD

**Issue by delta11** [w3c/css-validator#289]
A not too new CSS property that allows for applying a filter to the element background: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

MDN notes it as available since Chromium 76

**Comment by atomkind** [comment]
still not fully supported and triggering css-validation error

**Comment by JeffersonReal** [comment]
Just landed here for the same "Property backdrop-filter doesn't exist"

`.hero-header_filter {backdrop-filter: blur(1.5rem) contrast(1.05) saturate(1.4) brightness(0.95);}`

**Comment by zhuofan-16** [comment]
Should consider to add suport for it
