### ISSUE TITLE
Validator Does Not Recognize CSS Custom Variables

### ISSUE THREAD

**Issue by Eunomiac** [w3c/css-validator#295]
_(I realize this issue has been raised before, but they appear to be locked to collaborators and lack any recent updates, so I hope it's alright that I post this anew)_

Has there been any progress on this?  I've seen this issue being raised periodically over most of the past decade, but I tried using the [WC3 CSS Validation Service](https://jigsaw.w3.org/css-validator/validator) on my CSS and was flooded with a plethora of non-errors resulting from the validator's apparent inability to play nice with CSS variables.
### First three reported errors:
![image](https://user-images.githubusercontent.com/5692071/110440176-6269b580-8086-11eb-910b-18f23956367a.png)

### The relevant lines of CSS referenced in the above excerpt:
- **[62]** &nbsp;&nbsp;`background-image: radial-gradient(var(--dotBright), var(--dotDark));`
- **[561]** `--bgH2: linear-gradient(270deg, var(--accentUp2), var(--accentUp4), var(--accentUp2));`
- **[642]** `--maxHeightInput: calc(var(--lineHeightBody) * 1.2);`

I've been using CSS variables for years now, and I don't quite understand how a validator can be relevant for anything but the simplest applications of CSS without at least _some_ acknowledgment of the existence of custom CSS variables?

**Comment by ylafon** [comment]
fixed by #316
