### ISSUE TITLE
The validator is having a problem with custom properties.

### ISSUE THREAD

**Issue by adrianoenache** [w3c/css-validator#303]
Hello there

The validator is having a problem with custom properties.

To reproduce use the link below.
https://adrianoenache.dev.br/fcc-projects/responsive-web-design/tribute-page.html

I open an issue related to custom properties inside RGB and RGBA functions, in the markup validator, the same problem is happening here. Take a look at the link below.
https://github.com/w3c/markup-validator/issues/61
![bug-with-custom-properties](https://user-images.githubusercontent.com/3247230/120651997-b867b280-c455-11eb-8ca3-ac53da66078a.PNG)

Despite the error, it is working in the browsers I tested on mobile and desktop on Edge, Chrome, and Firefox. So I think this is a bug in the validator.

**Comment by ylafon** [comment]
fixed by #316 (now remains implementation of css-scrollbars)

**Comment by ylafon** [comment]
and scrollbar-related properties fixed by #318
