### ISSUE TITLE
Support :is() and :where()

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/css-validator#304]
Now that they are universally supported.... 

https://drafts.csswg.org/selectors-4/#matches

**Comment by ylafon** [comment]
Hum, it was added since quite a while, but there is a bug (and bigger than expected)

**Comment by marcoscaceres** [comment]
Appreciate the update!

**Comment by ylafon** [comment]
work started on the `selectors-4` branch, more soon!

**Comment by ylafon** [comment]
See bc5029573934b4136a930611b2348c69f1340f70 for :is() and :where(), 327615c79303971aadd1afa08bda58bc186a6e99 for :has() need more work for complex selectors and it should be a good time to merge.

**Comment by ylafon** [comment]
Fixed by 60a34e60ea54b537d3f0ec8909d6329c5337e223

**Comment by marcoscaceres** [comment]
Yay! Nice one @ylafon!!!
