### ISSUE TITLE
Parse error with custom properties in `calc()`

### ISSUE THREAD

**Issue by j9t** [w3c/css-validator#305]
Possible dup of #298:

A snippet like `foo{padding-left:calc(var(--leading-half) - 1px)}` leads to a parse error in the validator: “Value Error : padding-left Parse Error `1px)`”.

The snippet seems valid, however.

More context: The issue can currently be seen in production with the [default style sheet](https://d1cxmu1ofnef1v.cloudfront.net/setup/default.min.css) for frontenddogma.com.

**Comment by ylafon** [comment]
I guess it should be related to the current handing of var which might be incomplete when used in another function, so not really a dup.

**Comment by ylafon** [comment]
fixed by #316
