### ISSUE TITLE
min-block-size and max-block-size are not recognized as valid css properties

### ISSUE THREAD

**Issue by skorasaurus** [w3c/css-validator#306]
URL being validated or code to reproduce error:
The CSS at https://codepen.io/skorasaurus/pen/gOWmYYO

```
Property max-block-size doesn't exist : 
Property min-block-size doesn't exist : 
```

Both min-block-size and max-block-size are not recognized CSS properties in the validator at https://jigsaw.w3.org/css-validator/validator

Both properties are supported in stable versions of Edge, Chrome, Firefox, and Safari as of this writing. 

ref: https://developer.mozilla.org/en-US/docs/Web/CSS/min-block-size
https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size

https://drafts.csswg.org/css-logical/#propdef-min-block-size

**Comment by ylafon** [comment]
In progress, see 74591c27393bbdc4e0198b49b3a076a1dc6272fe and 29d1d192b4e681fbd9e92432185d85c0fd82f56b

**Comment by skorasaurus** [comment]
Thank you for the additional updates =)
