### ISSUE TITLE
Error with cubic-bezier(...) in variable

### ISSUE THREAD

**Issue by PiotrSss** [w3c/css-validator#325]
I've recently started using this https://midzer.github.io/tobii/dist/tobii.min.css and week ago it was ok (there was one error with `overscroll-behavior: contain`), but today I noticed that validator shows also errors when `--transition-timing-function: cubic-bezier(0.19, 1, 0.22, 1);` is used in `var(--transition-timing-function)`. Is it something you introduced unknowingly and can be corrected soon or is it there to stay for longer, because it's part of something bigger?

You can see it live on https://jigsaw.w3.org/css-validator/validator?uri=https://midzer.github.io/tobii/dist/tobii.min.css

**Comment by ylafon** [comment]
This is indeed a bug introduced by the handling of css variable (before that it was failing on var() in general, unless it was a  single value)

**Comment by ylafon** [comment]
Now in production, thanks for the report!
