### ISSUE TITLE
Validator crashes on scroll-snap-type

### ISSUE THREAD

**Issue by cerebralfornication** [w3c/css-validator#326]
1. What I did: Went to https://jigsaw.w3.org/css-validator/validator.html.en , clicked "Direct input", entered ".a {scroll-snap-type:x}", clicked "Check"
2. What I expected: Report of "Valid CSS", see https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type
3. What happened instead: "Inconsistent stackmap frames at branch target 310 Exception"

**Comment by ylafon** [comment]
strangely enough it works on some servers but not all of them. Investigating.

**Comment by ylafon** [comment]
Fixed by changing the... java compiler.
Thanks for the report!
