### ISSUE TITLE
Bug: SOAP response contains variables and function calls instead of the actual values

### ISSUE THREAD

**Issue by pvoglhofer** [w3c/css-validator#327]
It's vey easy to reproduce. Just open https://jigsaw.w3.org/css-validator/validator?text=invalid&output=soap12 for example.

The SOAP response contains the following wrong sections:
```
<m:uri>$esc.xml($file_title)</m:uri>
(...)
<m:errorlist>
        <m:uri>$sfe</m:uri>
                
            <m:error>
                <m:line>1</m:line>
                <m:errortype>parse-error</m:errortype>
                <m:context>$esc.xml($context_msg)</m:context>        
                <m:message>
        
                    $esc.xml($error_msg)
                </m:message>
            </m:error>
        
        </m:errorlist>
        
```

This makes it currently not possible to properly extract the validation errors when you're using the SOAP service.
I've attached the entire response for completeness.

[validator.txt](https://github.com/w3c/css-validator/files/7183606/validator.txt)

**Comment by ylafon** [comment]
Fixed, and thanks for reporting, this was due to missing updated dependency in external jar files.
