### ISSUE TITLE
Errors with Bootstrap 3.3.7 library

### ISSUE THREAD

**Issue by emem1975** [w3c/css-validator#330]
I use the library [https://jigsaw.w3.org/css-validator/validator?uri=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css](url) and week ago it was ok. But a few days ago, I noticed that the validator shows tons of errors. Is it an unconscious mistake or a desired action?

You can see it live on [https://jigsaw.w3.org/css-validator/validator?uri=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css](url)

**Comment by ylafon** [comment]
seems to be an issue relative to the handling of the first error, definitely a new bug.
The non-minified version works (but it has extra whitespace tokens).

**Comment by ylafon** [comment]
Fixed by 45688000e1f3d961b6b83645e75bb68b44866a0a (there is still one deprecation-related error, but it is a valid one)
