### ISSUE TITLE
Scientific notation is not properly supported in keyframe selectors

### ISSUE THREAD

**Issue by stof** [w3c/css-validator#332]
```
@keyframes a {
    from {
        content: 'b';
    }
    to {
        content: 'c';
    }
    25% {
        content: 'd';
    }
    1.5E1% {
        content: 'e';
    }
    1E1% {
        content: 'f';
    }
}
```

The CSS spec about `<percentage>` allows any `<number>` before the `%`, which includes number in scientific notation.
Both Firefox and Chromium parse the `1.5E1%` and `1E1%` properly, but this validator reports errors

**Comment by ylafon** [comment]
Fixed by https://github.com/w3c/css-validator/commit/988b7dccd52fcdaa359266b5df47d6b0f19795ce thanks for the report!

**Comment by ylafon** [comment]
spec link is https://www.w3.org/TR/2021/WD-css-values-4-20210715/#number-value (for reference)
