### ISSUE TITLE
Unicode range errors - may be a defect of the validator

### ISSUE THREAD

**Issue by rocc-o** [w3c/css-validator#354]
Hello, sorry to bother, but this issue is still happening whenever I put `unicode-range: U+20-22,U+26-2A,U+2C-3B,U+3F-5A,U+61-7A,U+A9,U+E8,U+E9,U+2014,U+2018,U+2019,U+201C,U+201D` for fonts subsettings, and it seems to be  [a bug in the validator](https://stackoverflow.com/questions/69697222/w3c-css-validator-is-giving-errors-on-font-face-unicode-range/69711789#69711789).
I'm missing something, or there's a way to solve this? Thanks!
![Screenshot 2021-12-04 at 16-46-09 Showing results for contents of text-input area - Nu Html Checker](https://user-images.githubusercontent.com/89341472/144715742-70c3be4a-56db-4ab2-8a22-0cda09ba1058.png)

**Comment by ylafon** [comment]
`unicode-range: U+20-22,U+26-2A,U+2C-3B,U+3F-5A,U+61-7A,U+A9,U+E8,U+E9,U+2014,U+2018,U+2019,U+201C,U+201D;` works well in the CSS Validator (see https://jigsaw.w3.org/css-validator/#validate_by_input ), so it may be that the [nu HTML Checker](https://github.com/validator/validator/) might not be up-to-date. I suggest filing an issue there. (pinging @sideshowbarker )

**Comment by rocc-o** [comment]
Sorry, my bad, I confused them with each other. I have now bookmarked https://jigsaw.w3.org/css-validator/
Thanks!

**Comment by sideshowbarker** [comment]
Thanks much for reporting this. I’ve pushed an update to https://validator.w3.org/nu/, so I believe this should now be working as expected there too.
