### ISSUE TITLE
Support `content-visibility`

### ISSUE THREAD

**Issue by Seirdy** [w3c/css-validator#362]
Current versions of WebKit (Safari) and Blink (Chrome, Edge, etc) support the `content-visibility` CSS property, and it will roll out to Firefox soon; [Firefox 100 will support parsing the property](https://bugzilla.mozilla.org/show_bug.cgi?id=1759130).

This CSS-validator and Nu both fail to parse `content-visibility`.

Contrived test-case:

``` css
footer {
  content-visibility: auto;
}
```

Real-world test-case: the `<style>` element for https://seirdy.one/

**Comment by xfq** [comment]
Link to spec: https://www.w3.org/TR/css-contain-2/#content-visibility

**Comment by ylafon** [comment]
Fixed by 3591111aab91501123d79a46f2b1704ba4b0d430
