### ISSUE TITLE
`border-inline-end-color` isn’t recognized

### ISSUE THREAD

**Issue by dieulot** [w3c/css-validator#367]
https://validator.w3.org/nu/#textarea:
> Error: CSS: border-inline-end-color: Property border-inline-end-color doesn't exist.

`border-inline-end-color`, `border-block-start-color` and `border-block-end-color` are otherwise okay.

My understanding:
✅ [/org/w3c/css/properties/css/CssBorderInlineEndColor.java](https://github.com/w3c/css-validator/blob/8332e44403c983c9e4046524231ee6fd634e0901/org/w3c/css/properties/css/CssBorderInlineEndColor.java) exists
❌ [/org/w3c/css/properties/CSS3Properties.properties](https://github.com/w3c/css-validator/blob/3591111aab91501123d79a46f2b1704ba4b0d430/org/w3c/css/properties/CSS3Properties.properties#L79-L80) doesn’t link to it.

**Comment by ylafon** [comment]
Thanks!
