### ISSUE TITLE
empty CSS variables not working

### ISSUE THREAD

**Issue by EmpireJones** [w3c/css-validator#368]
CSS variables should be clearable when set to an empty value.

```
* {
--brightness: ;
}
```

Results in `Parse Error`

This usage seems to be used by tailwind CSS.

**Comment by MichaIng** [comment]
Same was discussed here where CSS validator throws multiple errors when checking the default v5.2.0 Bootstrap CSS: https://github.com/twbs/bootstrap/issues/36508
