### ISSUE TITLE
content: "🚲"; is a Parse Error and content: "✂️" is not?

### ISSUE THREAD

**Issue by 1jj** [w3c/css-validator#378]
See https://validator.nu/?showsource=yes&doc=http%3A%2F%2Fflohmarkt-haundorf.de%2F

Is content: "🚲"; really an error?

**Comment by ylafon** [comment]
Looks like the page can't be checked by the CSS Validator, https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fflohmarkt-haundorf.de%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en reports a "Forbidden" from this server.

**Comment by 1jj** [comment]
URL is http://flohmarkt-haundorf.de/

No problem for me here ...
https://validator.w3.org/nu/?doc=http%3A%2F%2Fflohmarkt-haundorf.de%2F

**Comment by ylafon** [comment]
Note that it is not exactly the same codebase, that's why I am asking to check with the CSS Validator only, which is currently blocked by the `flohmarkt-haundorf.de` website.

**Comment by ylafon** [comment]
Fixed by #386
