### ISSUE TITLE
UnescapeFilterReader replaces \r with \n causing invalid localization of errors

### ISSUE THREAD

**Issue by AdrianSorop** [w3c/css-validator#393]
I validated a file that had \r\n as end line separator.
The localization of errors was off.
I managed to reduce the problem to the `org.w3c.css.util.UnescapeFilterReader`. It seems like the reader replaces \r with \n

Here's the quick unit test for the issue:

  ```
public void testUnescapeFilterReader() throws Exception {

    String content = 
        "x {\r\n"
            + "  content:leader(a,b,c);\r\n"
            + "}";

    UnescapeFilterReader unescapeFilterReader = new UnescapeFilterReader(new StringReader(content));

    StringBuilder sb = new StringBuilder();
    int l = 0;
    char c[] = new char[1024];
    while ((l = unescapeFilterReader.read(c)) > 0) {
      sb.append(new String(c, 0, l));
    }
    unescapeFilterReader.close();

    assertEquals(
        "x {\n"
            + "  content:leader(a,b,c);\n"
            + "}", 
            sb.toString());
  }
```

**Comment by ylafon** [comment]
Input is processed per https://www.w3.org/TR/2021/CRD-css-syntax-3-20211224/#input-preprocessing
But yes, it leads to some mismatch when you apply the line/col numbers to the original stream, which is mainly an issue for partially minimised CSS.
