### ISSUE TITLE
Value Error : font-variant super is not a font-variant value : super

### ISSUE THREAD

**Issue by mig281** [w3c/css-validator#397]
The error occurs for the following CSS:

```css
h5.my-class-name {
  font-variant: super;
}
```

Unless I'm misreading something, the [MDN documentation on `font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) gives both `sub` and `super` as a valid value of `font-variant`:

>`sub`, `super`
>Specifies the keywords and functions related to the [font-variant-position](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position) longhand property.

**Comment by ylafon** [comment]
Indeed, font-variant-position values are wrongly forgotten in the font-variant longhand parsing

**Comment by mig281** [comment]
Thank you for fixing this, @ylafon! 👏
