### ISSUE TITLE
Validator marks clear:both; as invalid

### ISSUE THREAD

**Issue by hamiltml** [w3c/css-validator#40]
Has anyone else encountered problems with the CSS validator (https://jigsaw.w3.org/css-validator/validator) suddenly marking pages that validated perfectly a week or more ago with invalid code? The invalid code marked by the validator seems to involve the clear property and its both value.

I did an experiment this morning by entering in these styles in the CSS validator on 11/4/15:

p {
clear: left;
}
Result: validated

p {
clear: right;
}
Result: validated

p {
clear: both;
}
Result: Error!

![warning](https://cloud.githubusercontent.com/assets/15656857/10947029/319ccea4-82eb-11e5-9da8-052e1a9f3043.jpg)

**Comment by Krinkle** [comment]
Getting the same. Not sure this makes sense. Clearly, `clear: both;` is not invalid CSS.

**Comment by ylafon** [comment]
I re-added 'both' as an acceptable value per CSS2.1 spec, waiting for confirmation by the CSS WG (see https://lists.w3.org/Archives/Public/www-style/2015Nov/0050.html )

**Comment by hamiltml** [comment]
Thank you! The code validates again.
