### ISSUE TITLE
The validator reports a seemingly valid linear-gradient value as invalid

### ISSUE THREAD

**Issue by epicbugs** [w3c/css-validator#43]
When a block of CSS containing

```css
background: linear-gradient(left, #7ac0da 0, #a4d4e6 100%);
```

gets fed into the [W3C CSS Validation Service by direct input](https://jigsaw.w3.org/css-validator/#validate_by_input) it gets caught as

> Value Error : background left is not a color value )

CSS documentation [over at Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Gradient_with_multiple_color_stops), however, seems to imply that such input is in fact valid.

**Comment by cvrebert** [comment]
Per MDN, it needs to be `to left`, not just `left`.

**Comment by ylafon** [comment]
Thanks @cvrebert . The example indeed validate with "to left".
The validator uses what is described in the MDN page as the "standard syntax" (Standard syntax (using the to keyword))
