### ISSUE TITLE
Can I run this locally just from the .jar?

### ISSUE THREAD

**Issue by ganego** [w3c/css-validator#45]
So I'm using the "Nu Html Checker" to check for html5 errors by just using the jar and giving it a file as an argument.

Now the documentation for css-validator states that I could use

>  java -jar css-validator.jar http://www.w3.org/

But this does not work, as there seem to be libraries missing?
Where can I see what libraries I would need?
Can I just download them and put them in this folder or would this not work?

Thank you

**Comment by sideshowbarker** [comment]
I don’t know what all the dependencies are, but it seems like we really should be building a single jar that includes all the dependencies, the way that `vnu.jar` does. Maybe @cvrebert could help with that. If not I can try doing it myself when I can make time, but it will be a while.

**Comment by cvrebert** [comment]
I'd be willing to help if switching to Maven is on the table. Not willing to spend time delving Ant's depths when that knowledge isn't going to be portable to other projects.
