### ISSUE TITLE
Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by manu4543** [w3c/css-validator#46]
I received following error on https://jigsaw.w3.org/css-validator/validator?uri=https://www.ixigo.com

URI : https://edge.ixigo.com/css/39d5e349508c3f42076f957d2b968946/ixigo/ui.home.v3.style.css
-1	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Although https://edge.ixigo.com/css/39d5e349508c3f42076f957d2b968946/ixigo/ui.home.v3.style.css is accessible otherwise.

**Comment by felipelalli** [comment]
Same issue here.

**Comment by ylafon** [comment]
Seems to be fixed now, maybe due to a new version of the JDK. Anyway, I am closing this, feel free to reopen if you find another site with TLS issues.
