### ISSUE TITLE
shorthand "flex" property expanded wrongly as to include "flex-flow"

### ISSUE THREAD

**Issue by FirefighterBlu3** [w3c/css-validator#53]
flex: 0 1 auto; is reported as "auto is not a flex-flow value : 0 1 auto"

flex is grow/shrink/basis: https://www.w3.org/TR/css-flexbox-1/#flex-property

**Comment by ylafon** [comment]
The current implementation of flex is based on a 2014 WD, will update now that we got a CR document.
