### ISSUE TITLE
user-select not recognized

### ISSUE THREAD

**Issue by nb000** [w3c/css-validator#54]
On validation I get the error:

> Property user-select doesn't exist : none

According to this [this spec](https://www.w3.org/TR/2000/WD-css3-userint-20000216#user-select), it is valid.

**Comment by ylafon** [comment]
See [http://www.w3.org/TR/2002/WD-css3-userint-20020802](http://www.w3.org/TR/2002/WD-css3-userint-20020802), this property is not defined at all in current specifications.

**Comment by cvrebert** [comment]
This property is defined in https://www.w3.org/TR/css-ui-4/#propdef-user-select
And the `none` value (at least) is widely supported: https://caniuse.com/#feat=user-select-none
@sideshowbarker Could this please be reopened?

**Comment by sideshowbarker** [comment]
Yeah at the time this was closed it was the right thing because there was no current WG draft published with `user-select` in it. Now that it’s in a current WG draft, I guess it makes sense to reopen this.
