### ISSUE TITLE
Ucn.properties should escape $span_value

### ISSUE THREAD

**Issue by jeremyweber-np** [w3c/css-validator#55]
When parsing errors occur on a test initiated from Unicorn, Unicorn is unable to handle the error and will only show something like:

A critical error has occurred.
class org.apache.xmlbeans.XmlException
error: Unexpected character encountered (lex state 3): '&'
org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3486)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1276)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1263)
org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
org.w3.x2009.x10.unicorn.observationresponse.ObservationresponseDocument$Factory.parse(Unknown Source)
org.w3c.unicorn.response.impl.DefaultResponseXBeans.<init>(DefaultResponseXBeans.java:60)
sun.reflect.GeneratedConstructorAccessor1015.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:526)
org.w3c.unicorn.response.ResponseFactory.getResponse(ResponseFactory.java:24)
org.w3c.unicorn.request.URIRequest.doRequest(URIRequest.java:141)
org.w3c.unicorn.RequestThread.run(RequestThread.java:66)

This can be fixed by properly escaping $span_value in ucn.properties

From:
```
#if ( $link_value )
		$error_content.get("link_before_parse_error") :  $error_content.get("link_name_parse_error") ($link_value)
#end
		$esc.xml($error_content.get("ErrorMsg"))
#if ( $span_value )
		$span_value
#end
```
To:
```
#if ( $link_value )
		$error_content.get("link_before_parse_error") :  $error_content.get("link_name_parse_error") ($link_value)
#end
		$esc.xml($error_content.get("ErrorMsg"))
#if ( $span_value )
		$esc.xml($span_value)
#end
```

**Comment by ylafon** [comment]
And in production now. Thanks!
