### ISSUE TITLE
Invalid toString() of "transform" property value

### ISSUE THREAD

**Issue by hannibal218bc** [w3c/css-validator#66]
The value of a CssTransform property object is a CssLayerList instance. The CssLayerList.toString() method concatenates multiple values by using ", " as separator.
https://github.com/w3c/css-validator/blob/master/org/w3c/css/values/CssLayerList.java#L87

While that is appropriate for CssFont and other properties with CssLayerList values,  for the "transform" property the function list must be whitespace-only separated (https://www.w3.org/TR/css-transforms-1/#typedef-transform-list) - or even not separated at all?
Browsers do not accept multiple transform-function values separated by commas, while whitespace is accepted.

Since CssLayerList is shared between properties that require and some what forbid commas, I guess either a distinct class or a new toString() method need to be introduced.

**Comment by ylafon** [comment]
Thanks!
