### ISSUE TITLE
Add support for @supports 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/css-validator#71]
Can you please add support for @ supports rule?

**Comment by marcoscaceres** [comment]
... or maybe change this to warning, instead of an error. It's preventing specs written using ReSpec from passing pub rules.

**Comment by palemieux** [comment]
See https://jigsaw.w3.org/css-validator/validator?uri=https://www.w3.org/TR/2017/WD-ttml-imsc1.0.1-20170323/

**Comment by ylafon** [comment]
Work started in the 'supports' branch, but not finished yet (as it require deeper changes than a regular \@rule)

**Comment by marcoscaceres** [comment]
@ylafon, great to hear. I'm wondering why @ supports is an error tho?

**Comment by devpaps** [comment]
I got a error today for @supports...

**Comment by raducoravu** [comment]
+1 for supporting "@supports". Like in:

            @supports (display: grid){
                body{
                    display: grid;
                    grid-template-rows: 100px 1fr 40px;
                    gird-template-columns: 170px 1fr;
                    grid-template-areas: 
                      "abc"
                      "def"
                      "hij";
                }
                header {
                    grid-area: header;
                }
            }
