### ISSUE TITLE
Bug: Empty Input Cannot Be Processed

### ISSUE THREAD

**Issue by niedzielski** [w3c/css-validator#73]
The [validator](https://jigsaw.w3.org/css-validator/validator) is unable to process empty input files and produces the following error both on direct input and empty file input:

```
CSS
Validator
Error
Target: No file

I/O Error: You have sent an invalid request.
```

**Comment by sideshowbarker** [comment]
What response would you want to have instead for the case where the input is empty?

**Comment by niedzielski** [comment]
Success is expected since no CSS is valid CSS. This configuration won't require tools that process multitudes of files to filter out empty inputs.
