### ISSUE TITLE
CSS validator throws "Servlet not configured properly"

### ISSUE THREAD

**Issue by bsullens** [w3c/css-validator#74]
I'm a college professor. I use the validators as part of my grading rubric. Students have alerted me that they cannot validate their CSS right now because of this error.  Please advise.

**Comment by ylafon** [comment]
Fixed. Thanks for the report.

**Comment by bsullens** [comment]
Wow! Thanks for the speedy response.  My students and I thank you.  My job would be so much more time-consuming without the two trusty validators. Many thanks!

Barry J. Sullens  
Assistant Professor
School of Computing and Informatics
Ivy Tech Community College-Northeast
Changing Lives. Making Indiana Great.

Phone: 260-480-2049 | Office Hours<http://www.sullens.net/>
Appointments: 260-480-4174 | Make an appointment<http://www.ivytech.edu/advising/appointment-help.html>
Coliseum Campus, Room CC2334 | 3800 North Anthony Boulevard | Fort Wayne, Indiana 46805

[id:image001.jpg@01D2388C.2D387FA0]
Disclaimer: This electronic message may contain information that is Proprietary, Confidential, or legally privileged or protected. It is intended only for the use of the individual(s) and entity named in the message. If you are not an intended recipient of this message, please notify the sender immediately and delete the material from your computer. Do not deliver, distribute or copy this message and do not disclose its contents or take any action in reliance on the information it contains.
