### ISSUE TITLE
Add support for validating "grid" display properties

### ISSUE THREAD

**Issue by raducoravu** [w3c/css-validator#86]
The CSS Validator should support Grid display properties like:

            @supports (display: grid){
                body{
                    display: grid;
                    grid-template-rows: 100px 1fr 40px;
                    gird-template-columns: 170px 1fr;
                    grid-template-areas: 
                      "abc"
                      "def"
                      "hij";
                }
                header {
                    grid-area: header;
                }
            }

**Comment by ylafon** [comment]
grid display properties are supported. In your example, the issue is that \@supports is not supported yet. See #71

**Comment by raducoravu** [comment]
@ylafon thanks for the details, I will try to update the validator we are using internal and test that the grid properties work for us.
